### ISSUE TITLE
How to use useInViewAnimate hook with mapping children components?

### ISSUE THREAD

**Issue by Vaasu-Dhand** [matthiaaas/framer-motion-hooks#1]
Hi, 
I have a Framer Motion animation that I want to run when the user is in the viewing viewport. So, I am using the useInViewAnimate Hook for the same. However, I cannot figure out how to make it work with a map function and a children animating component. I made a video, it's not the best but I tried to explain the situation. 
Here's the github repo - https://github.com/Vaasu-Dhand/vaasudhand

https://user-images.githubusercontent.com/64599364/113908822-99052e00-97f4-11eb-8758-d6610c277973.mp4

**Comment by matthiaaas** [comment]
Hey, thank you for the descriptive video!

I think you're already pretty close to getting what you want. The following code maps through a list `skills` and fades in all the skills as soon as their common parent element is visible in viewport by firing the `visible` animation variant.

```js
function Skills() {
  const { inViewRef, animation } = useInViewAnimate({
    animate: "visible"
  })

  return (
    <ul ref={inViewRef}>
      {skills.map((skill, i) => (
        <motion.li
          key={i}
          initial="initial"
          animate={animation}
          variants={variants}
        >
          {skill}
        </motion.li>
      ))}
    </ul>
  )
}

const variants = {
  initial: {
    opacity: 0
  },
  visible: {
    opacity: 1,
  }
}
```

This example does the same as the above, but also delays the items by 0.2s * index for each skill. This will very probably produce the expected result.

```js
function Skills() {
  const { inViewRef, animation } = useInViewAnimate({
    animate: "visible"
  })

  return (
    <ul ref={inViewRef}>
      {skills.map((skill, i) => (
        <motion.li
          key={i}
          custom={i}
          initial="initial"
          animate={animation}
          variants={variants}
        >
          {skill}
        </motion.li>
      ))}
    </ul>
  )
}

const variants = {
  initial: {
    opacity: 0
  },
  visible: i => ({
    opacity: 1,
    transition: {
      delay: i * 0.2
    }
  })
}
```

Let me know if you need any further help regarding this issue.

**Comment by Vaasu-Dhand** [comment]
Perfect! I got it working. Thanks :)
